import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        {/* Header Section */}
        <header className="bg-white shadow-md p-4">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <div className="flex items-center space-x-3">
              
              <Image
                src="/interface_ai_favicon.jpeg" 
                alt="Logo"
                width={32}
                height={32}
                className="object-contain"
              />
              <span className="text-xl font-bold">Interface.ai</span>
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main>{children}</main>

        {/* Footer Section */}
        <footer className="bg-white p-4 mt-8">
          <div className="max-w-7xl mx-auto text-center">
            <span className="text-sm text-gray-600">Submitted By: Gaurav Kumar Jha | Email: <a href="mailto:gauravjha8298@gmail.com" className="text-blue-600 hover:text-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500">gauravjha8298@gmail.com</a></span>
          </div>
        </footer>
      </body>
    </html>
  );
}
